openapi: 3.0.2
info:
  title: Paymentic Payments APIs
  version: 1.0.0
  description: It enable payments in PAYMENTIC platform
  contact:
    name: Claudio E. de Oliveira
    email: claudioed.oliveira@gmail.com
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
paths:
  /v1/payments:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/payment-request'
        required: true
      tags:
        - payments
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/payment-created'
          description: Payment created successfully
        '401':
          $ref: '#/components/responses/res-401'
        '403':
          $ref: '#/components/responses/res-403'
        '422':
          $ref: '#/components/responses/res-422'
        '500':
          $ref: '#/components/responses/res-500'
      security:
        -
          hydra:
            - payments.write
      operationId: create-payment
      summary: It creates a payment request
    parameters:
      -
        name: Idempotency-Key
        description: ''
        schema:
          type: string
        in: header
        required: true
components:
  schemas:
    buyer-info:
      title: buyer-info
      description: ''
      type: object
      properties:
        document:
          description: Buyer document
          type: string
        name:
          description: Buyer name
          type: string
      example:
        document: 570.278.648-35
        name: Joe Doe
    credit-card-info:
      title: credit-card-info
      description: ''
      type: object
      properties:
        card_info:
          type: string
        token:
          type: string
      example:
        card_info: CGGF1234ASS
        token: 28c80b82-3917-11ee-b450-325096b39f47
    error-401:
      title: error-401
      description: ''
      type: object
      properties:
        code:
          type: string
        description:
          type: string
      example:
        code: PAY-001
        description: invalid authentication
    error-403:
      title: error-403
      description: ''
      type: object
      properties:
        code:
          type: string
        description:
          type: string
      example:
        code: PAY-003
        description: insufficient permissions
    error-404:
      title: error-404
      description: ''
      type: object
      properties:
        code:
          type: string
        description:
          type: string
      example:
        code: PAY-404
        description: resource not found
    error-422:
      title: error-422
      description: ''
      type: object
      properties:
        code:
          type: string
        description:
          type: string
      example:
        code: PAY-002
        description: insufficient funds
    error-500:
      title: error-500
      description: ''
      type: object
      properties:
        code:
          type: string
        description:
          type: string
      example:
        code: PAY-500
        description: internal server error
    payment-created:
      title: payment-created
      description: ''
      type: object
      properties:
        id:
          type: string
      example:
        id: 28c8103c-3917-11ee-9d57-325096b39f47
    payment-orders:
      title: payments_orders
      description: ''
      type: object
      properties:
        seller_account:
          description: Which seller will receive the money
          type: string
        amount:
          description: The transaction amount for the order
          type: string
        currency:
          description: 'The currency for the order (ISO 4127[4])'
          type: string
        payment_order_id:
          description: A globally unique ID for this payment
          type: string
      example:
        seller_account: 28c80b82-3917-11ee-b450-325096b39f47
        amount: '20.48'
        currency: BRL
        payment_order_id: 28c808e4-3917-11ee-8fea-325096b39f47
    payment-request:
      title: payment-request
      description: ''
      required:
        - buyer_info
        - credit_card_info
        - payment_orders
      type: object
      properties:
        checkout_id:
          description: A globally unique ID for this checkout
          type: string
        buyer_info:
          $ref: '#/components/schemas/buyer-info'
          description: The information of the buyer
          properties:
            document:
              type: string
            name:
              type: string
        credit_card_info:
          $ref: '#/components/schemas/credit-card-info'
          description: >-
            This could be encrypted credit card information or a payment token. The value is
            PSP-specific.
          properties:
            card_info:
              type: string
            token:
              type: string
        payment_orders:
          description: A list of the payment orders.
          type: array
          items:
            $ref: '#/components/schemas/payment-orders'
      example:
        checkout_id: 28c80b82-3917-11ee-b450-325096b39f47
        buyer_info:
          document: 570.278.648-35
          name: Joe Doe
        credit_card_info:
          card_info: CGGF1234ASS
          token: 28c80b82-3917-11ee-b450-325096b39f47
        payment_orders:
          -
            seller_account: 28c80b82-3917-11ee-b450-325096b39f47
            amount: '20.48'
            currency: BRL
            payment_order_id: 28c808e4-3917-11ee-8fea-325096b39f47
  responses:
    res-500:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error-500'
      description: ''
    res-401:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error-401'
      description: ''
    res-403:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error-403'
      description: ''
    res-422:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error-422'
      description: ''
  securitySchemes:
    hydra:
      openIdConnectUrl: 'https://competent-cori-vgu1750x6j.projects.oryapis.com/.well-known/openid-configuration'
      type: openIdConnect
security:
  -
    hydra:
      - payments.write
      - payments.read
tags:
  -
    name: payments
    description: Payments Operations
